import { Content } from './helper-files/content-interfaces';

export const CONTENTList: Content[] = [{id: 1,
  author: 'Grant',
  body: 'this is me',
  type: 'player',
  imageUrl: 'https://cdn.discordapp.com/attachments/344161381244731403/444715149836943370/image.jpg' ,
  title: 'me'},
  {id: 2,
    title: 'Best Friend',
    body: 'this is my best friend',
    type: 'player',
    author: 'dylan'},
  {id: 3,
    author: 'ben',
    title: 'the salty one',
    type: 'player',
    body: 'my other best friend'},
  {id: 4,
    body: 'the plausibly insane one of my friend group',
    type: 'player',
    title: 'the human nuclear reactor on meltdown',
    author: 'austin'},
  {id: 5,
    body: 'the one with a god complex',
    title: 'the one who plays god alot',
    type: 'GM',
    author: 'Liam'}];
